### ISSUE TITLE
undefined method `sub' for ["-auto-orient", "-resize", "\"150x150>\""]:Array while working with Rails4 and Ruby2.0.0

### ISSUE THREAD

**Issue by Manju244** [railscasts/182-cropping-images#2]
Hi,

I am using mongoid-paperclip, Rails4.0.0 and ruby2.0.0.
Cropping is working fine also data is storing in the MangoDB database. But after submitting crop button its rising the error and not storing the cropped image.

NoMethodError in UploadsController#update 
undefined method `sub' for ["-auto-orient", "-resize", "\"150x150>\""]:Array

lib/paperclip_processors/cropper.rb:5:in `transformation_command'
app/models/upload.rb:47:in`reprocess_attachment'
app/controllers/uploads_controller.rb:77:in `block in update'
app/controllers/uploads_controller.rb:76:in`update'

cropper.rb

def transformation_command
if crop_command
crop_command + super.sub(/ -crop \S+/, '')
else
super
end

**Comment by Manju244** [comment]
Got it,

changed my cropper.rb file code

   def transformation_command 
     if crop_command 
       r = super 
       if r.class == Array 
         r = r.join(' ') 
       end 
       crop_command + r.sub(/ -crop \S+/, '') 
     else 
       super 
     end 

Thank You
If you have other simple solution post here....

**Comment by tddrmllr** [comment]
I'm having this same issue, and the solution laid out here throws my server into a never ending process.

**Comment by Manju244** [comment]
@violentj Please share the code...!!!

**Comment by tddrmllr** [comment]
I actually figured it out. The after_update callback to reprocess avatar was causing the infinite loop. So I moved the if cropping logic to the controller update action, and that fixed my problem.

**Comment by tddrmllr** [comment]
I actually figured it out. The after_update callback to reprocess avatar was causing the infinite loop. So I moved the if cropping logic to the controller update action, and that fixed my problem.

**Comment by Manju244** [comment]
Nice!!!

**Comment by guilb** [comment]
@violentj  Can you share your code, please ?
Thanks for advance

**Comment by awijeet** [comment]
You can check it here.
https://github.com/awijeet/Image_cropping_in_rails4

An  implementation

**Comment by haitaochen** [comment]
I do that following your codes ,and it did not work,please
